/*.
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package license;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author Gagan Amrit
 */
public class duplicate extends javax.swing.JFrame {
 String path,path1,spath,spath1;
 int c1=0,c2=0;
    /**
     * Creates new form duplicate
     */
  String str;
    Connection con;
    static int id,mobile;
    ResultSet rs;
    Statement st;
    String name;
    exchange e=new exchange();
    public duplicate()
    {
        initComponents();
this.getContentPane().setBackground(Color.WHITE);
        setBounds(100,100,750,700);
        setTitle("Duplicate Licence");
        id=e.get_id();
        name=e.get_name();
        tf_id.setText(Integer.toString(id));
        tf_name.setText(name);
        mobile=e.mobile();
        tf_mobile.setText(Integer.toString(mobile));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        tf_mobile = new javax.swing.JTextField();
        jb_request = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jb_proof = new javax.swing.JButton();
        l_proof = new javax.swing.JLabel();
        l_fir = new javax.swing.JLabel();
        jb_fir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_reason = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 90, 40, 30);

        tf_id.setEnabled(false);
        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });
        getContentPane().add(tf_id);
        tf_id.setBounds(300, 90, 230, 30);

        tf_mobile.setEnabled(false);
        tf_mobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_mobileActionPerformed(evt);
            }
        });
        getContentPane().add(tf_mobile);
        tf_mobile.setBounds(300, 230, 230, 30);

        jb_request.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb_request.setText("Request");
        jb_request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_requestActionPerformed(evt);
            }
        });
        getContentPane().add(jb_request);
        jb_request.setBounds(300, 310, 120, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Mobile");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(150, 220, 90, 40);

        jb_proof.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb_proof.setText("Upload proof");
        jb_proof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_proofActionPerformed(evt);
            }
        });
        getContentPane().add(jb_proof);
        jb_proof.setBounds(500, 310, 180, 30);
        getContentPane().add(l_proof);
        l_proof.setBounds(410, 350, 190, 190);
        getContentPane().add(l_fir);
        l_fir.setBounds(100, 350, 190, 190);

        jb_fir.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jb_fir.setText("Upload FIR");
        jb_fir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_firActionPerformed(evt);
            }
        });
        getContentPane().add(jb_fir);
        jb_fir.setBounds(70, 310, 170, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Name");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 130, 90, 40);

        tf_name.setEnabled(false);
        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });
        getContentPane().add(tf_name);
        tf_name.setBounds(300, 140, 230, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel2.setText("Duplicate License");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(250, 10, 260, 60);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Reason");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 180, 90, 40);

        tf_reason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_reasonActionPerformed(evt);
            }
        });
        getContentPane().add(tf_reason);
        tf_reason.setBounds(300, 190, 230, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_mobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_mobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_mobileActionPerformed

    private void jb_requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_requestActionPerformed
        // TODO add your handling code here:
        
        if(tf_id.getText().equals("")||tf_mobile.getText().equals("")||tf_name.getText().equals("")||tf_reason.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "all fields are compulsory");              
        }
        else if(c1==0)
        {
            JOptionPane.showMessageDialog(this, "upload FIR");
        }
        else if(c2==0)
        {
            JOptionPane.showMessageDialog(this,"upload proof");
        }
        else
        {
              connection();
              id=Integer.parseInt(tf_id.getText());
            try
            {
               str="select id1,mobile from register where id1="+id+" and mobile="+Integer.parseInt(tf_mobile.getText());
                st=con.createStatement();
                rs=st.executeQuery(str);
                if(rs.next())
                {
                    
                    st.close();
                    copy(path,id,c1);
                    copy(path1,id,c2);
                    str="insert into duplicate(id1,mobile,fir,proof) values("+id+","+Integer.parseInt(tf_mobile.getText())+",'"+spath+"','"+spath1+"'"+")";
                    st=con.createStatement();
                    int result=st.executeUpdate(str);
                    if(result==1)
                    {
                        JOptionPane.showMessageDialog(this, "Request successful");
                        this.dispose();
                    }
                }
            }
            catch (Exception ex)
            {
               ex.printStackTrace();
            }
            
            
        }
        
    }//GEN-LAST:event_jb_requestActionPerformed

    private void jb_firActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_firActionPerformed
        // TODO add your handling code here:
        upload();
    }//GEN-LAST:event_jb_firActionPerformed

    private void jb_proofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_proofActionPerformed
        // TODO add your handling code here:
        upload1();
    }//GEN-LAST:event_jb_proofActionPerformed

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameActionPerformed

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
      
       
    }//GEN-LAST:event_tf_idActionPerformed

    private void tf_reasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_reasonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_reasonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(duplicate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(duplicate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(duplicate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(duplicate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new duplicate().setVisible(true);
            }
        });
    }
      void upload()
    {
        JFileChooser jf=new JFileChooser();
        int option=jf.showOpenDialog(this);
        if(option==0)
        {
            path=jf.getSelectedFile().getAbsolutePath();
            JOptionPane.showMessageDialog(this,"pic uploaded");
            BufferedImage img=null;
            try
            {
                img= ImageIO.read(new File(path));
                
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
            Image dimg = img.getScaledInstance(190, 190,Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(dimg);
            l_fir.setIcon(icon);
            c1=1;
        }
      
        else
        {
            JOptionPane.showMessageDialog(this,"try again");
        }
    }
       void upload1()
    {
        JFileChooser jf=new JFileChooser();
        int option=jf.showOpenDialog(this);
        if(option==0)
        {
            path1=jf.getSelectedFile().getAbsolutePath();
            JOptionPane.showMessageDialog(this,"pic uploaded");
            BufferedImage img=null;
            try
            {
                img= ImageIO.read(new File(path1));
                
            }
            catch(Exception e)
            {
                e.printStackTrace();
            }
            Image dimg = img.getScaledInstance(190, 190,Image.SCALE_SMOOTH);
            ImageIcon icon=new ImageIcon(dimg);
            l_proof.setIcon(icon);
            c2=2;
        }
      
        else
        {
            JOptionPane.showMessageDialog(this,"try again");
        }
    }
         void copy(String path,int id,int c)
    {
        if(c==1)
        {
            spath="e:\\duplicate\\"+id+"fir.jpg";
            image(path,spath);
        }
        else if(c==2)
        {
            spath1="e:\\duplicate\\"+id+"proof.jpg";
            image(path,spath1);
        }
    }
          void image(String path,String spath)
    {
         try {
            InputStream input_file=new FileInputStream(path);
            OutputStream output_file=new FileOutputStream(spath);
            byte[] mypic=new byte[1024];
            int len;
            while((len=input_file.read(mypic))>0)
            {
                output_file.write(mypic, 0, len);
            }
            output_file.close();
            input_file.close();
         }
         catch(Exception e)
         {
            e.printStackTrace();
         }
    }
         void connection()
      {
           try
        {
        Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
        con=DriverManager.getConnection("jdbc:odbc:varun","sa","chandigarh");
        //JOptionPane.showMessageDialog(rootPane, "connected");
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jb_fir;
    private javax.swing.JButton jb_proof;
    private javax.swing.JButton jb_request;
    private javax.swing.JLabel l_fir;
    private javax.swing.JLabel l_proof;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_mobile;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_reason;
    // End of variables declaration//GEN-END:variables
}
