/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package license;
import java.awt.Color;
import java.sql.*;
import java.sql.DriverManager;
import javax.swing.*;

/**
 *
 * @author sony
 */
public class newlogin extends javax.swing.JFrame {

    /**
     * Creates new form newlogin
     */
    int s;
    Connection con;
    Statement st;
    ResultSet rs;
   static  String name;
   int id;
    public newlogin() {
        initComponents();
this.getContentPane().setBackground(Color.WHITE);
        setBounds(100,100,500,500);
        setTitle("Login");
        try
        {
           Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
           con=DriverManager.getConnection("jdbc:odbc:varun","sa","chandigarh");
           //JOptionPane.showMessageDialog(this, "connected");
         
        }
        catch(Exception  e)
        {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_pass = new javax.swing.JPasswordField();
        tf_id = new javax.swing.JTextField();
        tb_login = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 204));
        setForeground(new java.awt.Color(102, 255, 102));
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 0, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("USER ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 90, 60, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PASSWORD ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 140, 90, 30);

        tf_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_passActionPerformed(evt);
            }
        });
        getContentPane().add(tf_pass);
        tf_pass.setBounds(120, 140, 220, 30);

        tf_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_idActionPerformed(evt);
            }
        });
        getContentPane().add(tf_id);
        tf_id.setBounds(120, 90, 220, 30);

        tb_login.setBackground(new java.awt.Color(255, 255, 255));
        tb_login.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tb_login.setForeground(new java.awt.Color(0, 0, 153));
        tb_login.setText("LOGIN");
        tb_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_loginActionPerformed(evt);
            }
        });
        getContentPane().add(tb_login);
        tb_login.setBounds(150, 220, 140, 50);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("user");
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(380, 100, 70, 23);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton2.setText("admin");
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(380, 130, 80, 23);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_passActionPerformed

    private void tb_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_loginActionPerformed
        // TODO add your handling code here:
        if(tf_id.getText().equals("")||tf_pass.getText().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "all fields are mandatory");
        }
        else if(buttonGroup1.isSelected(null))
        {
           JOptionPane.showMessageDialog(this,"select user type");
        }
        
        else
        {
            if(jRadioButton1.isSelected())
            {
             String str="select id1,name,mobile from register where id1="+tf_id.getText()+" and "+"password='"+tf_pass.getText()+"'";
             //JOptionPane.showMessageDialog(this, str);
               
                           
             try
             {
              st=con.createStatement();
              rs=st.executeQuery(str);
              
                      if(rs.next())
                      {
                       
                          JOptionPane.showMessageDialog(this, "Access Granted");
                         
                              
                          exchange ex1=new exchange();
                        
                          ex1.set(rs.getInt(1),rs.getString(2),rs.getInt("mobile"));
                          User obj=new User();
                          obj.setVisible(true);
                        this.dispose();
                          
                          
                      }
                      else
                      {
                        
                        
                          JOptionPane.showMessageDialog(this,"Access Denied");
                      }
                      
                            
             }
             catch(Exception e)
             {
                 e.printStackTrace();
             }
             
       
        }
            else if(jRadioButton2.isSelected())
            {
                String str="select * from admin where admin='"+tf_id.getText()+"' and "+"pass='"+tf_pass.getText()+"'";
                try
                {
                   st=con.createStatement();
                  rs=st.executeQuery(str);
              
                      if(rs.next())
                      {
                       
                          JOptionPane.showMessageDialog(this, "Access Granted");  
                          adminx ad=new adminx();
                          ad.setVisible(true);
                          this.dispose();
                }
                      else
                      {
                          JOptionPane.showMessageDialog(this, "Aceess denied");
                      }
                }
                catch(Exception e)
                {
                    e.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_tb_loginActionPerformed

    private void tf_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newlogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newlogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton tb_login;
    private javax.swing.JTextField tf_id;
    private javax.swing.JPasswordField tf_pass;
    // End of variables declaration//GEN-END:variables
}
