/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package license;

import javax.swing.JOptionPane;

/**
 *
 * @author sony
 */
public class start extends javax.swing.JFrame  {

    
   start x;
    public start() {
        initComponents();
        setBounds(100, 100, 520, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jb_login = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jb_request = new javax.swing.JButton();
        jb_about = new javax.swing.JButton();
        jb_rules = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(718, 478));
        getContentPane().setLayout(null);

        jb_login.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jb_login.setForeground(new java.awt.Color(0, 0, 204));
        jb_login.setText("Login");
        jb_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_loginActionPerformed(evt);
            }
        });
        getContentPane().add(jb_login);
        jb_login.setBounds(520, 90, 160, 50);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Demi", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Choose Service");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 30, 320, 50);

        jb_request.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jb_request.setForeground(new java.awt.Color(204, 0, 0));
        jb_request.setText("New License");
        jb_request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_requestActionPerformed(evt);
            }
        });
        getContentPane().add(jb_request);
        jb_request.setBounds(490, 10, 210, 60);

        jb_about.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jb_about.setForeground(new java.awt.Color(153, 0, 153));
        jb_about.setText("About Us");
        jb_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_aboutActionPerformed(evt);
            }
        });
        getContentPane().add(jb_about);
        jb_about.setBounds(10, 20, 150, 60);

        jb_rules.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jb_rules.setForeground(new java.awt.Color(255, 0, 204));
        jb_rules.setText("Rules");
        jb_rules.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_rulesActionPerformed(evt);
            }
        });
        getContentPane().add(jb_rules);
        jb_rules.setBounds(570, 410, 120, 50);

        jButton1.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 204));
        jButton1.setText("Administrator");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 350, 190, 50);

        jButton2.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(136, 53, 53));
        jButton2.setText("Gallery");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 410, 160, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 710, 480);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_loginActionPerformed
        // TODO add your handling code here:
       
        
        newlogin obj=new newlogin();
         obj.setVisible(true);
         this.dispose();
       
    }//GEN-LAST:event_jb_loginActionPerformed

    private void jb_requestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_requestActionPerformed
        signup sn=new signup();
        sn.setVisible(true);
    }//GEN-LAST:event_jb_requestActionPerformed

    private void jb_rulesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_rulesActionPerformed
        // TODO add your handling code here:
         ru1 obj=new ru1();
        obj.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jb_rulesActionPerformed

    private void jb_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_aboutActionPerformed
        // TODO add your handling code here:
         rla obj=new rla();
        obj.setVisible(true);
        this.dispose(); 
       
        
    }//GEN-LAST:event_jb_aboutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
new Patil_sir().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
new g1().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(start.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new start().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jb_about;
    private javax.swing.JButton jb_login;
    private javax.swing.JButton jb_request;
    private javax.swing.JButton jb_rules;
    // End of variables declaration//GEN-END:variables
}
